name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    permissions:
      contents: read
      
    strategy:
        matrix:
            os: [ubuntu-latest, macos-latest, windows-latest]
            
    runs-on: ${{ matrix.os }}
    
    steps:
        - name: Chekcout code
          uses: actions/checkout@v4
         
        - name: Configure CMake
          run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=RelWithDebInfo
         
        - name: Build
          # Use --config to specify the build type for multi-config generators
          run: cmake --build ${{github.workspace}}/build --config RelWithDebInfo
          
        - name: Run tests
          working-directory: ${{github.workspace}}/build
          run: ctest -C RelWithDebInfo --output-on-failure
        
        
